SELECT TOP (1000) [OrderDate]
      ,[StockDate]
      ,[OrderNumber]
      ,[ProductKey]
      ,[CustomerKey]
      ,[TerritoryKey]
      ,[OrderLineItem]
      ,[OrderQuantity]
  FROM [sales].[dbo].[Sales Data 2020]
